use Sales
create table Customer(
Customer_id int primary key,
Customer_name varchar(30),
city varchar(15),
grade int ,
salesman_id int references Salesman(salesman_id)
)
 select *  from Customer
 insert into Customer values(3002 ,'Nick Rimando ',  'New York'  ,  100   ,   5001)
 insert into Customer values  (    3007 ,' Brad Davis'     , 'New York ',     200  ,      5001)
 insert into Customer values   (   3005  ,'Graham Zusi'  ,   'California' ,   200  ,       5002)
 insert into Customer values     (  3008  ,'Julian Green'    ,'London'  ,      300   ,      5002)
 insert into Customer values ( 3004  ,'Fabian Johnson',  'Paris'       ,  300       ,  5006)
 insert into Customer values(3009,  'Geoff Cameron',   'Berlin'    ,    100   ,      5003)
 insert into Customer values(3003 , 'Jozy Altidor ',   'Moscow '   ,    200    ,     5007)
 insert into Customer values   (3001  ,'Brad Guzan'  ,    'London '    ,  100 ,       5005)

--2.Write a SQL statement to display specific columns like name and commission for all the salesmen
select name,commission from Salesman

--3.Write a query to display the columns in a specific order like order date, salesman id, order number and purchase amount from for all the orders
select ord_date,salesman_id,ord_no,purch_amt from Orders

--4.	write a SQL query to find the salespeople who lives in the City of 'Paris'. Return salesperson's name, city.
select name,city from Salesman where city='Paris'

--5.	write a SQL query to find those customers whose grade is 200. Return customer_id, cust_name, city, grade, salesman_id
 select * from Customer where grade=200

 --6.	write a SQL query to find the orders, which are delivered by a salesperson of ID. 5001. Return ord_no, ord_date, purch_amt
select ord_no,ord_date,purch_amt from Orders where salesman_id=5001

--write a SQL query to count number of orders by the combination of each order date and salesperson. Return order date, salesperson id.
select ord_date,salesman_id,count(ord_no) 
from Orders 
group by ord_date,salesman_id

--write a SQL query to count number of salespeople who belongs to a city. Return number of salespeople.
select  count(*) from Salesman where city is not Null

--write a SQL query to count all the orders generated on '2012-08-17'. Return number of orders.
select count(ord_no) from orders where order_date='2012-08-17'

--write a SQL query to find the maximum order (purchase) amount generated by each salesperson. Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.).
-- Return salesperson id and maximum purchase amount
select salesman_id,max(purch_amt) from orders where salesman_id>=5003 and salesman_id<=5008 group by salesman_id
--or
select salesman_id,max(purch_amt) from orders group by salesman_id having salesman_id between 5003 and 5008